# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sm6225-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter borneo capri caprip devon guamp hawao rhode,$(TARGET_DEVICE)),)

endif
