# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sm6225-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter borneo capri caprip cebu guam guamna guamp devon hawao rhode,$(TARGET_DEVICE)),)

endif
